### ISSUE TITLE
Adding a New Command

### ISSUE THREAD

**Issue by Bailuse** [hkva/fabric-discord-integration#10]
I want to add a /Whitelist command please add thank you

**Comment by hkva** [comment]
Ok, I added a new command - `mc!rcon` that lets admins forward commands to the server console.
You can use it to add players to a whitelist like this: `mc!rcon whitelist add UserName`

To give a Discord user rcon access you just need to add their user ID to `rconUsers` in the config file. ([Example](https://gist.github.com/hkva/50f368241f65a877d26a3546f979a7f7)) and run `/discord loadConfig`
