### ISSUE TITLE
Using commands?

### ISSUE THREAD

**Issue by GamingWithFusion** [hkva/fabric-discord-integration#12]
I tried using the mc!rcon command using Discord to send commands to the console, as per what the intended use is. I attempted to use the basic game mode command.

> mc!rcon gamemode creative username

I did not have success, nothing is working. 

`{
  "token": "bot token inserted",
  "commandPrefix": "mc!",
  "relayChannelIDs": [
	 relay ID added
],
  "rconUsers": [ User 1, User 2 ]
}` 

This is in relation to the new command from #11

**Comment by hkva** [comment]
Thanks for reporting this. Fixed with f8a0e7d78e0fb5c21af95fdbd99ac5ced312870c

You can download the new release here: https://github.com/hkva/fabric-discord-integration/releases/tag/v1.4.1
