### ISSUE TITLE
Latest version not compatible with 20w51a?

### ISSUE THREAD

**Issue by HeyItsJono** [hkva/fabric-discord-integration#6]
Hiya!
The latest version says it's compatible with snapshot 20w51a, but when I throw it into the mods folder of the server, it throws this error upon starting the server:
`Could not find required mod: discord requires {minecraft @ [1.17-alpha.20.49.a]}`

Any help would be greatly appreciated :)

**Comment by hkva** [comment]
Sorry about that. Fixed in cbe7ded85a7d39eed72b4142fc57cd31e096325f, I'll upload a new release now.

**Comment by hkva** [comment]
Alright, I tested and uploaded the new release here: https://github.com/hkva/fabric-discord-integration/releases/tag/v1.2.2
