### ISSUE TITLE
On versioning

### ISSUE THREAD

**Issue by hkva** [hkva/fabric-discord-integration#7]
I'm thinking of overhauling how the project publishes builds with respect to Minecraft updates. Currently, we increment the patch number every time we upgrade the mod to support a new game version, but I don't think this is right since most of these builds actually change nothing and would be backwards-compatible. 

Here's the new way I'm thinking of doing it:
- Only increment the mod version number when mod code changes
- Release jars with the following naming scheme: `fabric-discord-integration-<major>-<minor>-<patch>+<minecraft version>.jar` (like the [fabric API](https://github.com/FabricMC/fabric/releases))
- Create GitHub releases for each mod version, attaching a build for each game version supported by that mod version.
- Have the master branch target the current release version of the game and have snapshot support on a different branch.

**Comment by hkva** [comment]
cc @SpaceClouds42 (if you care) since this change would break any future pull requests you plan on submitting.

**Comment by SpaceClouds42** [comment]
> cc @SpaceClouds42 (if you care) since this change would break any future pull requests from your fork.

Thanks for letting me know, I'll be sending a patch later today (hopefully). Noticed some issues with the way formatting was dealt with, just haven't gotten around to fixing it yet

**Comment by hkva** [comment]
Going ahead with this
